# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20160830_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='shouldDarkenHeader',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
