# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 02:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20160829_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img_link',
            field=models.CharField(default=django.utils.timezone.now, max_length=2000),
            preserve_default=False,
        ),
    ]
